name: Measure performance impacts
description: Runs a Zeebe benchmark and compares metrics with and without artifical chaos

inputs:
  name:
    description: 'Specifies the name of the performance test'
    required: true
  chaos:
    description: 'Name of the chaos that will be introduced between measurements'
    default: network-latency-35
    required: false

runs:
  using: composite
  steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'zeebe-cluster'
          location: 'europe-west1-b'
      - run: ./setup.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}
      - run: ./measure.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}
      - run: ./chaos.sh
        env:
          CHAOS: ${{ inputs.chaos }}
          BENCHMARK_NAME: ${{ inputs.name }}
      - run: ./measure.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}