name: Measure Performance Impact
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Specifies the name of the performance test'
        required: true
      chaos:
        description: 'Name of the chaos that will be introduced between measurements'
        default: network-latency-35
        required: false
concurrency:
  group: ${{ github.event.inputs.name }}
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'zeebe-cluster'
          location: 'europe-west1-b'
      - run: ./setup.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}
  measure-before:
    runs-on: ubuntu-latest
    needs: [ setup ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - run: ./measure.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}
  deploy-chaos:
    runs-on: ubuntu-latest
    needs: [ measure-before ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'zeebe-cluster'
          location: 'europe-west1-b'
      - run: ./chaos.sh
        env:
          CHAOS: ${{ inputs.chaos }}
          BENCHMARK_NAME: ${{ inputs.name }}
  measure-after:
    runs-on: ubuntu-latest
    needs: [ deploy-chaos ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - run: ./measure.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}