name: Measure
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Specifies the name of the performance test'
        required: true

jobs:
  measure:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/628707732411/locations/global/workloadIdentityPools/zeebe-gh-actions/providers/gha-provider'
          service_account: 'zeebe-gh-actions@zeebe-io.iam.gserviceaccount.com'
      - uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'zeebe-cluster'
          location: 'europe-west1-b'
      - run: ./run.sh
        env:
          BENCHMARK_NAME: ${{ inputs.name }}